#! /bin/bash

set -xe

SSH_ORIGINAL_COMMAND="bin/secret-shell --action enrol test ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOI+485EYOY2s6rRYumsQmif2DRZD/FaaXKw67yeML0GuEft08rZDPMXYewk6lrjl05hqQUz5CVLKvcPbhNW9d4=" bin/secret-shell --principal admin --ssh
SSH_ORIGINAL_COMMAND="bin/secret-shell --action group.list " bin/secret-shell --principal admin --ssh
SSH_ORIGINAL_COMMAND="bin/secret-shell --action group.create users" bin/secret-shell --principal admin --ssh 
SSH_ORIGINAL_COMMAND="bin/secret-shell --action group.member_add users test" bin/secret-shell --principal admin --ssh
echo foo | SSH_ORIGINAL_COMMAND="bin/secret-shell --action secret.put a b" bin/secret-shell --principal admin --ssh
SSH_ORIGINAL_COMMAND="bin/secret-shell --action acl.set users read,write a" bin/secret-shell --principal admin --ssh
echo some_secret | SSH_ORIGINAL_COMMAND="bin/secret-shell --action secret.put a b c" bin/secret-shell --principal test --ssh
SSH_ORIGINAL_COMMAND="bin/secret-shell --action secret.get a b c" bin/secret-shell --principal test --ssh
SSH_ORIGINAL_COMMAND="bin/secret-shell --action enrol norights ssh-rsa asdf" bin/secret-shell --principal admin --ssh
SSH_ORIGINAL_COMMAND="bin/secret-shell --action secret.get a b c" bin/secret-shell --principal norights --ssh
